#ifndef OK_OPERATOR_H
#define OK_OPERATOR_H

#include "token.h"

typedef enum {
  OPERATOR_UNDEFINED = 0,
  OPERATOR_PLUS,
  OPERATOR_MINUS,
  OPERATOR_ASTERISK,
  OPERATOR_SLASH,
  OPERATOR_MODULO,
  OPERATOR_CARET,
  OPERATOR_BANG,
  OPERATOR_EQUAL,
  OPERATOR_BANG_EQUAL,
  OPERATOR_GREATER,
  OPERATOR_GREATER_EQUAL,
  OPERATOR_LESS,
  OPERATOR_LESS_EQUAL,
  OPERATOR_CALL, // fr?
  OPERATOR_SUBSCRIPT,
  OPERATOR_AMPERSAND,
  OPERATOR_BAR,
  OPERATOR_TILED,
  OPERATOR_PLUS_PLUS,
  OPERATOR_MINUS_MINUS,
  OPERATOR_ASTERISK_EQUAL,
  OPERATOR_SLASH_EQUAL,
  OPERATOR_MODULO_EQUAL,
  OPERATOR_CARET_EQUAL,
  OPERATOR_AMPERSAND_EQUAL,
  OPERATOR_BAR_EQUAL,
  OPERATOR_SHIFT_LEFT,
  OPERATOR_SHIFT_RIGHT,
  OPERATOR_SHIFT_LEFT_EQUAL,
  OPERATOR_SHIFT_RIGHT_EQUAL,
} operator_type;

#endif // OK_OPERATOR_H
